### ISSUE TITLE
Hi, can you share me the dataset？

### ISSUE THREAD

**Issue by TachibanaYoshino** [xjunming/iciar2018-challenge#1]
I am waiting for the dataset examination,  Can you easily share the dataset? Thank you ！
![image](https://user-images.githubusercontent.com/36946777/66714808-23322900-edee-11e9-82e0-ded88395ab6d.png)
![image](https://user-images.githubusercontent.com/36946777/66714811-2a593700-edee-11e9-8bfa-d5b6a27f4732.png)

**Comment by xjunming** [comment]
你好！这个是我在公司做项目，但数据集我没有迁移回来，十分抱歉！
